
name: WDIO-CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:           
            - name: Install Chromium
              run: sudo apt-get install chromium-browser
            - uses: actions/checkout@v4
            - name: Use Node.js 
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependecies
              run: npm install 
            - name: Running tests
              run: npm run wdio    